// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvnsUVvPYjbnOR6FcOG2Xwc4mZXJoo_TU',
    appId: '1:869608176701:web:65618b5a077faf9c63fe54',
    messagingSenderId: '869608176701',
    projectId: 'carpooling-a5e4c',
    authDomain: 'carpooling-a5e4c.firebaseapp.com',
    storageBucket: 'carpooling-a5e4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATtkqCoC0TJVW16oA8K3xARiHlay5H9Ww',
    appId: '1:869608176701:android:c3983c77986f5e6163fe54',
    messagingSenderId: '869608176701',
    projectId: 'carpooling-a5e4c',
    storageBucket: 'carpooling-a5e4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Y4p4_vyMyEmgkTUL_kEYZbWRzWf5SuQ',
    appId: '1:869608176701:ios:b7dfdafe27d7ceb463fe54',
    messagingSenderId: '869608176701',
    projectId: 'carpooling-a5e4c',
    storageBucket: 'carpooling-a5e4c.appspot.com',
    androidClientId: '869608176701-t9pcp8foa6rgv9f67rpcggr1hhjds6t2.apps.googleusercontent.com',
    iosClientId: '869608176701-f2pf6t3emnjgc0eg1k4m1giodnlhm9jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.carPooling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Y4p4_vyMyEmgkTUL_kEYZbWRzWf5SuQ',
    appId: '1:869608176701:ios:e18d13bd17e7451463fe54',
    messagingSenderId: '869608176701',
    projectId: 'carpooling-a5e4c',
    storageBucket: 'carpooling-a5e4c.appspot.com',
    androidClientId: '869608176701-t9pcp8foa6rgv9f67rpcggr1hhjds6t2.apps.googleusercontent.com',
    iosClientId: '869608176701-dkhvbblk1vhjkpc5r4n6f87cqoeip504.apps.googleusercontent.com',
    iosBundleId: 'com.example.carPooling.RunnerTests',
  );
}
